% Student Grade Analyzer - MATLAB Visualization
% This script reads CSV output files generated by the Python analyzer
% and visualizes grade statistics and distributions.

% Read summary statistics
summary = readtable("C:\Users\vaani\student-grade-analyzer\outputs\summary.csv");

% Read grade distribution
dist = readtable("C:\Users\vaani\student-grade-analyzer\outputs\grade_distribution.csv");

%% Plot 1: Grade Distribution
figure;
bar(categorical(dist.grade), dist.count);
xlabel("Letter Grade");
ylabel("Number of Students");
title("Grade Distribution");
grid on;

%% Plot 2: Summary Statistics
figure;
values = summary.value;
labels = summary.metric;

bar(categorical(labels), values);
xlabel("Metric");
ylabel("Value");
title("Summary Grade Statistics");
grid on;
